server:
  port: 8001

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

cloud:
  discovery:
    enabled: true
    locator:
      enabled: true
      lower-case-service-id: true
